/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppProfileIndexRouteImport } from './routes/_app/profile/index'
import { Route as AppLiveIndexRouteImport } from './routes/_app/live/index'
import { Route as AppHomeIndexRouteImport } from './routes/_app/home/index'
import { Route as AppHistogramIndexRouteImport } from './routes/_app/histogram/index'
import { Route as AppContentListIndexRouteImport } from './routes/_app/content/list/index'
import { Route as AppContentCreateIndexRouteImport } from './routes/_app/content/create/index'
import { Route as AppContentCategoryIndexRouteImport } from './routes/_app/content/category/index'
import { Route as AppContentEditIdRouteImport } from './routes/_app/content/edit/$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileIndexRoute = AppProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AppRoute,
} as any)
const AppLiveIndexRoute = AppLiveIndexRouteImport.update({
  id: '/live/',
  path: '/live/',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeIndexRoute = AppHomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => AppRoute,
} as any)
const AppHistogramIndexRoute = AppHistogramIndexRouteImport.update({
  id: '/histogram/',
  path: '/histogram/',
  getParentRoute: () => AppRoute,
} as any)
const AppContentListIndexRoute = AppContentListIndexRouteImport.update({
  id: '/content/list/',
  path: '/content/list/',
  getParentRoute: () => AppRoute,
} as any)
const AppContentCreateIndexRoute = AppContentCreateIndexRouteImport.update({
  id: '/content/create/',
  path: '/content/create/',
  getParentRoute: () => AppRoute,
} as any)
const AppContentCategoryIndexRoute = AppContentCategoryIndexRouteImport.update({
  id: '/content/category/',
  path: '/content/category/',
  getParentRoute: () => AppRoute,
} as any)
const AppContentEditIdRoute = AppContentEditIdRouteImport.update({
  id: '/content/edit/$id',
  path: '/content/edit/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginIndexRoute
  '/register': typeof RegisterIndexRoute
  '/histogram': typeof AppHistogramIndexRoute
  '/home': typeof AppHomeIndexRoute
  '/live': typeof AppLiveIndexRoute
  '/profile': typeof AppProfileIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/content/edit/$id': typeof AppContentEditIdRoute
  '/content/category': typeof AppContentCategoryIndexRoute
  '/content/create': typeof AppContentCreateIndexRoute
  '/content/list': typeof AppContentListIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/login': typeof LoginIndexRoute
  '/register': typeof RegisterIndexRoute
  '/histogram': typeof AppHistogramIndexRoute
  '/home': typeof AppHomeIndexRoute
  '/live': typeof AppLiveIndexRoute
  '/profile': typeof AppProfileIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/content/edit/$id': typeof AppContentEditIdRoute
  '/content/category': typeof AppContentCategoryIndexRoute
  '/content/create': typeof AppContentCreateIndexRoute
  '/content/list': typeof AppContentListIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/login/': typeof LoginIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/_app/histogram/': typeof AppHistogramIndexRoute
  '/_app/home/': typeof AppHomeIndexRoute
  '/_app/live/': typeof AppLiveIndexRoute
  '/_app/profile/': typeof AppProfileIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/content/edit/$id': typeof AppContentEditIdRoute
  '/_app/content/category/': typeof AppContentCategoryIndexRoute
  '/_app/content/create/': typeof AppContentCreateIndexRoute
  '/_app/content/list/': typeof AppContentListIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/histogram'
    | '/home'
    | '/live'
    | '/profile'
    | '/settings'
    | '/content/edit/$id'
    | '/content/category'
    | '/content/create'
    | '/content/list'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/histogram'
    | '/home'
    | '/live'
    | '/profile'
    | '/settings'
    | '/content/edit/$id'
    | '/content/category'
    | '/content/create'
    | '/content/list'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/login/'
    | '/register/'
    | '/_app/histogram/'
    | '/_app/home/'
    | '/_app/live/'
    | '/_app/profile/'
    | '/_app/settings/'
    | '/_app/content/edit/$id'
    | '/_app/content/category/'
    | '/_app/content/create/'
    | '/_app/content/list/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/': {
      id: '/_app/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/live/': {
      id: '/_app/live/'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof AppLiveIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home/': {
      id: '/_app/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/histogram/': {
      id: '/_app/histogram/'
      path: '/histogram'
      fullPath: '/histogram'
      preLoaderRoute: typeof AppHistogramIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/content/list/': {
      id: '/_app/content/list/'
      path: '/content/list'
      fullPath: '/content/list'
      preLoaderRoute: typeof AppContentListIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/content/create/': {
      id: '/_app/content/create/'
      path: '/content/create'
      fullPath: '/content/create'
      preLoaderRoute: typeof AppContentCreateIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/content/category/': {
      id: '/_app/content/category/'
      path: '/content/category'
      fullPath: '/content/category'
      preLoaderRoute: typeof AppContentCategoryIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/content/edit/$id': {
      id: '/_app/content/edit/$id'
      path: '/content/edit/$id'
      fullPath: '/content/edit/$id'
      preLoaderRoute: typeof AppContentEditIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppHistogramIndexRoute: typeof AppHistogramIndexRoute
  AppHomeIndexRoute: typeof AppHomeIndexRoute
  AppLiveIndexRoute: typeof AppLiveIndexRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppContentEditIdRoute: typeof AppContentEditIdRoute
  AppContentCategoryIndexRoute: typeof AppContentCategoryIndexRoute
  AppContentCreateIndexRoute: typeof AppContentCreateIndexRoute
  AppContentListIndexRoute: typeof AppContentListIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppHistogramIndexRoute: AppHistogramIndexRoute,
  AppHomeIndexRoute: AppHomeIndexRoute,
  AppLiveIndexRoute: AppLiveIndexRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppContentEditIdRoute: AppContentEditIdRoute,
  AppContentCategoryIndexRoute: AppContentCategoryIndexRoute,
  AppContentCreateIndexRoute: AppContentCreateIndexRoute,
  AppContentListIndexRoute: AppContentListIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
