-- Create categories table
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create articles table
create table if not exists public.articles (
  id bigint generated by default as identity primary key,
  title text not null,
  content text,
  category_id bigint references public.categories(id),
  status text check (status in ('draft', 'published')) default 'draft',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
