-- Create categories table
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create articles table
create table if not exists public.articles (
  id bigint generated by default as identity primary key,
  title text not null,
  content text,
  category_id bigint references public.categories(id),
  status text check (status in ('draft', 'published')) default 'draft',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create profiles table (Links to auth.users)
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text,
  nickname text,
  avatar_url text,
  gender text,
  phone text,
  bio text,
  updated_at timestamp with time zone
);

-- Create login_logs table
create table if not exists public.login_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  ip_address text,
  device text,
  login_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Function to handle new user creation
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, nickname)
  values (new.id, new.email, split_part(new.email, '@', 1));
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to automatically create profile on signup
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
